name=input("What is your name?")
print(name)
name=input("Enter your Name?")
print("Hello,",name)
name=input("Enter your Name:")
age=input("Enter your Age:")
city=input("Enter your City:")
dream_job=input("Enter your dream job:")
print("\n...................Syudent Information................")
print("Name:",name)
print("Age:",age)
print("City:",city)
print("Your Dream Job:",dream_job)